version: "3.8"

services:


  redis:
    image: redis
    ports: 
      - 6379:6379

  api:
    build: ./images/api
    command: ["npm", "run", "dev"]
    ports:
      - 3000:3000
    environment:
      - REDIS_URI
    volumes:
      - ./images/api/src:/usr/app/src
    
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: startDB

  osc:
    build: ./images/oscSender
    command: ["npm", "run", "dev"]
    ports:
      - 3001:3000
    environment:
      - REDIS_URI
    volumes:
      - ./images/oscSender/src:/usr/app/src
    
